import xlwings as xw #Only module that needs pip installing
import os
import re
from Utilities import *
import logging
import datetime
import calendar


# Functions --------------------------------------------------------------------------------------------------------------------------------

def get_unique_path(x,
                    y=0):
        """
        Iteratively checks if a file exists and generates a unique file name by appending a counter.
        
        Usage: get_unique_path(file_path)

        Returns: unique file name (path)

        Expected input:
            A default file path, and the details dictionary
        Expected output:
            A unique file path corresponding to the values in details
        """
        # Extract the file name and extension
        file_name, file_extension = os.path.splitext(x)
        suffix = os.path.basename(file_name)
        folder = os.path.dirname(file_name)
        # Construct the current file name to check
        if "index" in details:
            current_file_name = f"{folder}\\{int(details['job_number'])}-{details['index'].replace('-','').replace(' ','')} {suffix}{file_extension}"
            while os.path.exists(current_file_name):
                y += 1
                current_file_name = f"{folder}\\{int(details['job_number'])}-{details['index'].replace('-','').replace(' ','')}({y}) {suffix}{file_extension}" 
        else:
            current_file_name = f"{folder}\\{int(details['job_number'])} {suffix}{file_extension}"
            # Check if the file exists
            while os.path.exists(current_file_name):
                y += 1
                current_file_name = f"{folder}\\{int(details['job_number'])} {suffix}({y}){file_extension}" 
        # Creates new directory if it doesn't exist
        j = os.path.dirname(current_file_name)
        if not os.path.exists(j):
            os.makedirs(j)
        return current_file_name
def pdf_maker(source,
              sheet_name1, 
              note_type):
    '''
    Copies a sheet from a source Excel book and exports it to a .pdf 
    with a unique file path, generated by get_unqiue_path

    Usage: pdf_maker(source_book, sheet_name, note_type)

    Returns: unique file path generated by get_unique_path, for later use

    Expected input: 
        A source file path, a sheet name, the note type
    Expected output:
        A uniquely named pdf version of the named sheet, that located at the
        source path
    '''
    try:
        logging.info(f"Creating pdf '{sheet_name1}', from '{source}'")
        with xw.App(visible=False) as app:
            destination = pdf_names[note_type]
            source_sheet, source_book = safe_book_opener(app,
                                                         source,
                                                         sheet_name1)
            unique_path = get_unique_path(destination) #function only used within this function
            source_sheet.api.ExportAsFixedFormat(0,
                                                 unique_path)
            pop_up(
                f"{pdf_names[sheet_name1]} has been created at:\n {truncater(unique_path, pdf_names['root'])}", 
                file = unique_path
                )
        return unique_path
    except FileNotFoundError as e:
            message = f"File not found at '{source}', '{sheet_name1}' has not been created."
            error_handling("Error", 
                           "pdf_maker()", 
                           e, 
                           is_critical = True, 
                           user_message = message)
            raise FileNotFoundError(message) from e
    except Exception as e:
        message = f"An unexpected error has occurred\n{sheet_name1} has not been created"
        error_handling("Error",
                       "pdf_maker()", 
                       e, 
                       is_critical = True, 
                       user_message = message)
        raise ExcelError(message) from e
def cell_reader(path_):
    '''
    Takes a given path, opens a workbook and specific sheet, then takes values from 
    specific cells to populate the 'Details' dictionary with.
    
    Usage: cell_reader(path_to_excel_workbook)

    Returns: details dictionary

    Expected input:
        A file path to a control document containing the delivery note sheet
    Expected output:
        Values for customer name and project reference added to the details
        dictionary
    '''
    try:
        
        logging.info(f"Opening Source Workbook at {path_}")
        details_ = {"job_number": ""}
        app = xw.App(visible = False)
        sheet_Del_note, source_book = safe_book_opener(app, 
                                                       path_,
                                                       "Del Note")
        sales_inv_sheet = safe_sheet_opener(source_book, "Sales Inv")
        details_["job_number"] = sheet_Del_note["F14"].value
        if isinstance(details_["job_number"],
                      (int, float)):
            details_["job_number"] = str(int(details_["job_number"]))
        customer_name = sheet_Del_note["C7"].value
        project_ref = sheet_Del_note["F19"].value
        invoice_date = sales_inv_sheet["E13"].value
        details_.update({"customer_name" : customer_name,
                         "project_ref" : project_ref,
                         "invoice_date" : invoice_date})
        source_book.close()
        return details_
    except KeyError as e:
        message = "Key error when reading 'Job Number'"
        error_handling("Error", 
                       "Dictionary creating and appending",
                        e,
                        is_critical = True, 
                        user_message = message)
        raise KeyError(message) from e
    except Exception as e:
        message = f"An unexpected error has occurred"
        error_handling("Error", 
                       "cell_reader()", 
                       e,
                       is_critical = True,
                       user_message = message)
        raise ExcelError(message) from e
def folder_namer_date(directory):
    jn = details["job_number"]
    inv_date_year = details["invoice_date"].year
    inv_date_month = details["invoice_date"].month
    inv_date_month_name = calendar.month_abbr[inv_date_month]
    if inv_date_month <10:
        inv_date_month = str(f"0{inv_date_month}")
    for name in os.listdir(directory):
        if f"{inv_date_year}-{inv_date_month} {inv_date_month_name}" in name:
            return name
    return f"{inv_date_year}-{inv_date_month} {inv_date_month_name} {jn} -"
def folder_namer(path_to_sales_inv_folder):
    '''
    Using details dictionary this function takes the 'job_number' and uses data validation 
    to ensure that only numeric (including numbers featuring a '-') are passed through, and 
    non-numeric values are caught. From this it uses the 0-99 naming convention and creates 
    the file paths for the folders corresponding to the 'job_number'.

    Usage: folder_namer()

    Returns: delivery_notes_folder_name, sales_invoices_folder_name

    Expected input:
        Nothing
    Expected result:
        Folders for the 'Sales Invoice' and 'Delivery Note' with a name
        that spans the 0-99 range around the given 'Job Number' 
    '''
    try:
        logging.info("Checking for index")
        if "-" in details["job_number"]:
            logging.info("Index found. Separating 'Job Number' and index.")
            error_handling("Warning", 
                           "Job Number with index", 
                           "Index Found",
                           is_critical = False)
            jn, index  = re.split(r'[- ]',details["job_number"],1)
            logging.info(f"Storing Job Number: '{jn}'")
            details["job_number"] = jn
            logging.info(f"Storing index: '{index}'")

            details.update({"index":index.replace(" ","").replace("-","")})
            if not details["index"].isnumeric():
                message = "The index on the 'Delivery Note number' contains non-numeric characters!"
                error_handling("Warning",
                               f"folder_namer(): {message}",
                               user_message = message)

    except ValueError as e:
        message = "An error has occured while trying to read the job number, please check it is in the standard format: XXXXXX or XXXXXX-XX"
        error_handling("Error", 
                       "Job Number integerisation", 
                       e,
                       is_critical = True, 
                       user_message = message)
        raise Exception(message) from e
    logging.info("Successfully integerised job number.")  
    try: 
        logging.info("Naming 'Delivery Note', and 'Sales Invoices' inner files")
        logging.info(f"Integrising 'Job Number'")
        jn = int(details["job_number"])
        rd_jn =int(jn/100) * 100
        folder_dn = f"Del_Notes {rd_jn} - {rd_jn+99}"
        folder_si = folder_namer_date(path_to_sales_inv_folder)
        return folder_dn, folder_si
    except ValueError as e:
        message = "An error has occured while trying to read the job number, please ensure that it is a numerical value"
        error_handling("Error", 
                       message, 
                       is_critical = True, 
                       user_message = message)
    except OverflowError as e:
        message = "'Job Number' too long. Process Aborted!"
        error_handling("Error",
                       f"Job Number division created overflow Error: {message}",
                       e,
                       is_critical = True,
                       user_message = message)
    except Exception as e:
        message = f"An unexpected error has occurred while finding 'Sales Invoices' and 'Delivery Notes' folders."
        error_handling("Error",
                       "Inner folder creation for 'Sales Invoice' and 'Delivery note'.",
                       e,
                       is_critical = True, 
                       user_message = message)

    

# Main Code -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
if __name__ == "__main__": 
    def main():
        # Logging -----------------------------------------------------------------------------------------------------------------------------------   
        '''
        -------------------------------------------------------------------------------------------------------------------------
        The code below contains a pop up to let the user know the process has begun, as the process can take a number of seconds
        to complete.
        
        Also below, is the function logger() (defined in the utilities.py file), that is used to configure the log file to store 
        errors. It creates a new folder for it within the working directory if one doesn't already exists. RotatingFileHandler()
        will create a new log file after the first one reaches as size of > Mb, it does this until there are five full files, then 
        it overwrites the first.
        -------------------------------------------------------------------------------------------------------------------------

        '''
        pop_up(" ⏳ Creating 'Sales Invoice' and 'Delivery Note' from current data.",t = 1000)
        logger(__file__) 
        
        # Paths -------------------------------------------------------------------------------------------------------------------------------------
        
        
        '''
        -------------------------------------------------------------------------------------------------------------------------
        The folowing code reads the "config.json" file and stores it as a dictionary that contains file paths and directory
        elements.

        Again the main json_reader() function definition has been moved the the utilities.py file.
        -------------------------------------------------------------------------------------------------------------------------
        '''

        global details, pdf_names #setting dictionaries as global to prevent unnecessary arguments in functions

        config_name = 'config.json'
        config, config_path = json_reader(config_name)
        drive = config["drive"]
        root = config["root"] #Using config.json file's stored variables in script
        type_del_note = config["type_del_note"]
        type_sales_inv = config["type_sales_inv"]
        default_path = config["default_path"]
        sales_inv_folder_path = config["sales_inv_folder_path"]
        logging.info(f"'{config_name}' read successfully. Values for: '{root}',"\
                     f"'{type_del_note}','{type_sales_inv}' and '{default_path}'"\
                     f" all read in from '{config_path}'.")
    
        '''
        -------------------------------------------------------------------------------------------------------------------------
        The following functions checks for any system arguments that should've been handed over by the Excel macro. 
        If the arguments are not present it notifies the user and defaults to a standard path for testing purposes.
        -------------------------------------------------------------------------------------------------------------------------
        '''
        path = get_excel_file_path(default_path)
        
        '''
        -------------------------------------------------------------------------------------------------------------------------
        The following code creates a dictionary "details" to allow free passing of its contained values through the various functions
        in this program it. The function itself opens the source book (i.e. the Control Document), opens the correct sheets, and sets
        the "job_number" value in the details dictionary to its correct value as given by the Delivery Note. Further it gathers the 
        Cutomer Name and Project reference names from the control document sheet to be used later in the naming of the .pdf's.
        -------------------------------------------------------------------------------------------------------------------------
        '''
        details = cell_reader(path)
        
        '''
        -------------------------------------------------------------------------------------------------------------------------
        The function below checks to see if the Delivery Note/Job Number has any dashes (i.e. 12345-6), and separates the index
        (i.e. 12345 and 6). It then sets the Delivery Note/Job Number to an integer to avoid any unwanted decimals.

        Then the job number value is manipulated in order to give the span of 0-99 ranges that the folders are divided into 
        (i.e Delivery Notes 12300-12399).
        -------------------------------------------------------------------------------------------------------------------------
        '''
        folder_name_dn, folder_name_si = folder_namer(sales_inv_folder_path)

        '''
        -------------------------------------------------------------------------------------------------------------------------
        Below is the intial dictionary created with the .pdf names, that are constructed from various elements that have been 
        read/produced so far.
        -------------------------------------------------------------------------------------------------------------------------
        '''
        # Save Names for pdf's -----------------------------------------------------------------------------------------------------------------------
        pdf_names = {
                    "sales_invoice_pdf" : f"{root}{type_sales_inv}\\{folder_name_si}\\{details['customer_name'].strip()} {details['project_ref'].strip()} Sales Invoice.pdf",                    
                    "del_note_pdf" : f"{root}{type_del_note}\\{folder_name_dn}\\{details['customer_name'].strip()} {details['project_ref'].strip()} Delivery Note.pdf",
                    "reverse_charge_pdf" : f"{root}{type_sales_inv}\\{folder_name_si}\\{details['customer_name'].strip()} {details['project_ref'].strip()} Reverse Charge.pdf",
                    "Sales Inv" : "Sales Invoice", 
                    "Del Note" : "Delivery Note", 
                    "Reverse Charge" : "Reverse Charge", 
                    "root" : root
                    }

        '''
        -------------------------------------------------------------------------------------------------------------------------
        Below is where the functions responsible for copying and exporting the Excel sheets to pdf's are utilised. The pdf's are 
        stored in their corresponding assigned folders. As each file is created a pop up message is generated to alert the user.

        Both of these functions are contained in separate try and except blocks to catch any individual errors, as well as an
        overall block to catch any KeyErrors. The KeyError will also give the user a pop up to alert them that something has gone
        wrong.

        Finally, the clean_up() function is run to close any Excel books that may remain open.
        -------------------------------------------------------------------------------------------------------------------------
        '''
        with ThreadPoolExecutor() as executor:

            executor.submit(pdf_maker,
                            path, 
                            "Del Note", 
                            note_type = "del_note_pdf" )
                            
            rev_charge_flag = pop_up("Does this job require a Reverse Charge?", 
                                 close = False, 
                                 option = True, 
                                 async_mode = False)
            
            if rev_charge_flag:
                pdf_maker(path, "Reverse Charge", 
                        note_type = "reverse_charge_pdf")
            else: 
                executor.submit(pdf_maker,
                            path, 
                            "Sales Inv", 
                            note_type = "sales_invoice_pdf")

            
            

        '''
        -------------------------------------------------------------------------------------------------------------------------
        The below code asks the user if they need a reverse charge document to be produced. This then sets the "rev_charge_flag"
        variable to True, then allows the pdf_maker() function to be run for the "Reverse Charge" sheet.
        -------------------------------------------------------------------------------------------------------------------------
        '''
        
        
        clean_up()

    try:
        main()
        logging.info("Run end ================================================================================================================================================================================================\n\n\n")
    except ValueError as e:
        pass
    except SheetError as e:
        pass
    except KeyError as e:
        pass
    except OverflowError as e:
        pass
    except Exception as e:
        message = f"Critical Error!\nProcess has been cancelled!"
        error_handling("Error","main()", e,
                       is_critical = True, user_message = message)
        raise Exception(message) from e